config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'shop', to: 'static_pages#shop'

  resources :reservations, only: %i[index create]
  post 'reservations/confirm'
  post 'reservations/back'

  resources :contacts, only: %i[index create]
  post 'contacts/confirm'
  post 'contacts/back'

  resources :users, only: %i[new create]
  get '/mypage', to: 'users#show'
  get '/mypage/edit', to: 'users#edit'
  patch '/mypage/edit', to: 'users#update'
  post 'users/confirm'
  post 'users/back'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: %i[new create edit update]

  resources :news, only: %i[index show]
  resources :menus, only: %i[index]

  namespace :admin do
    root 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    post 'guest_login', to: 'user_sessions#guest_login'
    delete 'logout', to: 'user_sessions#destroy'
    resources :news
    resources :menus
    resources :users, only: %i[index show edit update destroy]
    resources :reservations
    patch '/reservations/cancel/:id', to: 'reservations#cancel', as: :cancel
    patch '/reservations/status/:id', to: 'reservations#status_update', as: :status
    resources :contacts, only: %i[index show update destroy]
    resources :capacities, only: %i[index show edit update]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :capacity

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  VALID_PHONE_REGEX = /\A\d{10,11}\z/.freeze

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: 'は正しいメールアドレスを入力してください' }, length: { maximum: 256 }
  validates :phonenumber, presence: true, format: { with: VALID_PHONE_REGEX, message: 'は正しい電話番号を入力してください' }, length: { in: 10..11 }
  validates :number_of_people, presence: true
  validates :visiting_time, presence: true
  validates :reservation_status, presence: true
  validates :capacity_id, presence: true

  validate :date_before_today, on: :create # 新規予約登録時のみバリデーションを適用する
  validate :not_reservation_capacity_status

  enum visiting_time: {
    '11:00': 0,
    '11:30': 1,
    '12:00': 2,
    '12:30': 3,
    '13:00': 4,
    '13:30': 5,
    '14:00': 6
  }

  enum reservation_status: {
    visiting: 0,
    visited: 1,
    cancel: 2
  }

  enum reservation_media: {
    web: 0,
    phone: 1,
    sns: 2,
    others: 3
  }

  # 予約日が今日以前の日付を制限するバリデーション
  def date_before_today
    errors.add(:start_time, 'は過去の日付は選択できません') if capacity.start_time < Time.zone.today
  end

  # capacityのステータスによってバリデーションを発生させる。
  def not_reservation_capacity_status
    case capacity.capacity_status
    when 'closed'
      errors.add(:start_time, 'は休業日です。')
    when 'full'
      errors.add(:start_time, 'は予約ができませんでした。一度店舗までご連絡下さい。')
    end
  end

  # 席数から予約人数をマイナスする
  def decreased_capacity
    capacity.remaining_seat - number_of_people
  end

  # 席数に変更人数をプラスする
  def increased_capacity
    capacity.remaining_seat + number_of_people
  end

  # 予約人数分、席数を変更する
  def change_capacity
    capacity.update!(remaining_seat: decreased_capacity)
  end

  # 席数を予約人数分戻す
  def return_capacity
    capacity.update!(remaining_seat: increased_capacity)
  end

  # 予約ステータスをキャンセル済みに変更する
  def status_cancel
    update!(reservation_status: 'cancel')
  end

  # 席数が０になった際にステータスを満席に更新する
  def full?
    capacity.update!(capacity_status: 'full') if capacity.remaining_seat.zero?
  end

  # 席数が０以外になった際にステータスを空席に更新する
  def vacancy?
    capacity.update!(capacity_status: 'vacancy') if capacity.remaining_seat != 0
  end

  # 予約ステータスを来店済みに更新
  scope :status_visitesd, -> { update(reservation_status: 'visited') }

  # 今日の予約かつステータスが来店予約のデータを取得する
  scope :today_reservation, -> { where(reservation_status: 'visiting', capacity_id: Capacity.today_id) }

  # 今日の予約件数を習得する
  scope :count_today_reservation, -> { where(capacity_id: Capacity.today_id).count }

  # capacityのデータを取得
  scope :search_capacity, -> { includes(:capacity) }

  # 日付を降順
  scope :date_desc, -> { order(capacity_id: 'desc') }

  # capacityを降順
  scope :capacity_desc, -> { search_capacity.date_desc }

  # 今日の予約かつステータスが来店予約のデータを取得する
  scope :today_reservation, -> { where(reservation_status: 'visiting', capacity_id: Capacity.today_id) }

  # 今日の予約かつステータスが来店予約のデータの件数を習得する
  scope :count_today_reservation, -> { today_reservation.count }

  # 作成から一週間以内のものを降順にで取得するscopeを呼び出す
  include Recent
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < Admin::BaseController
  before_action :set_reservation, only: %i[show edit update destroy cancel status_update]
  before_action :assign_to_capacity_id, only: %i[create update]

  def index
    @q = Reservation.ransack(params[:q])
    @reservations = @q.result.capacity_desc.page(params[:page])
  end

  def show; end

  def new
    @reservation = Reservation.new
  end

  def create
    Reservation.transaction do
      @reservation = Reservation.create!(reservation_params.merge(capacity_id: @capacity_id)) # 選択された日付に紐づいたcapacity_idを挿入し予約を作成
      @reservation.change_capacity                                                            # 予約日に紐づくcapacityから予約人数をマイナスする
      @reservation.full?                                                                      # 席数が0になった場合にcapacityステータスを満席に変更する。
    end
    redirect_to admin_reservations_path, success: '予約が完了しました'
  rescue StandardError => e
    redirect_to new_admin_reservation_path, danger: e.message
  end

  def edit; end

  def update
    Reservation.transaction do
      @reservation.return_capacity                                              # 変更前の予約日に紐づくcapacityに変更前の予約人数をプラスする(capacityを元に戻す)
      @reservation.vacancy?                                                     # 席数が0以外になった場合にcapacityステータスを空席に変更する。
      @reservation.update!(reservation_params.merge(capacity_id: @capacity_id)) # 変更後の選択された日付に紐づいたcapacity_idを挿入し予約を更新
      @reservation.change_capacity                                              # 変更後の予約日に紐づくcapacityから予約人数をマイナスする
      @reservation.full?                                                        # 席数が0になった場合にcapacityステータスを満席に変更する。
    end
    redirect_to admin_reservations_path, success: '予約の変更が完了しました'
  rescue StandardError
    flash.now['danger'] = '予約の変更ができませんでした'
    render :edit
  end

  def status_update
    if @reservation.update!(reservation_params) # 他テーブルの値を絡めないステータス更新用
      redirect_to admin_reservations_path, success: '変更が完了しました'
    else
      flash.now['danger'] = '更新に失敗しました'
      render :show
    end
  end

  def destroy
    Reservation.transaction do
      @reservation.return_capacity # 予約日に紐づくcapacityに変更前の予約人数をプラスする(capacityを元に戻す)
      @reservation.vacancy?        # 席数が0以外になった場合にcapacityステータスを空席に変更する。
      @reservation.destroy!
    end
    redirect_to admin_reservations_path, success: '予約を削除しました'
  end

  def cancel
    Reservation.transaction do
      @reservation.return_capacity # 予約日に紐づくcapacityに変更前の予約人数をプラスする(capacityを元に戻す)
      @reservation.vacancy?        # 席数が0以外になった場合にcapacityステータスを空席に変更する。
      @reservation.status_cancel   # 予約ステータスをキャンセル済みに変更(予約自体のデータは残す)
    end
    redirect_to admin_reservations_path, success: 'キャンセルが完了しました'
  rescue StandardError
    flash.now['danger'] = 'キャンセルできませんでした'
    render :show
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def assign_to_capacity_id
    @capacity_id = Capacity.find_by(start_time: params[:reservation][:capacity_id]).id # 選択された日付に紐づくcapacity_idを呼び出す
  end

  def reservation_params
    params.require(:reservation).permit(:name, :email, :phonenumber, :number_of_people, :visiting_time, :reservation_status, :capacity_id, :user_id, :reservation_media, :remarks)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservation = Reservation.new
  end

  def confirm
    capacity_id = Capacity.find_by(start_time: params[:reservation][:capacity_id]).id  # 選択された日付に紐づくcapacity_idを呼び出す
    @reservation = Reservation.new(reservation_params.merge(capacity_id: capacity_id)) # 選択された日付に紐づいたcapacity_idを挿入し予約を作成
    return unless @reservation.invalid?                                                # バリデーションに引っかかった場合のレンダリング

    flash.now[:danger] = "ご選択頂いたご来店日は#{@reservation.capacity.capacity_status_i18n}です。"
    view_context.reservation_error_to_slack
    render :index
  end

  def back
    @reservation = Reservation.new(reservation_params) # 入力した値を保持したままフォームへ戻る
    render :index
  end

  def create
    Reservation.transaction do
      @reservation = Reservation.create!(reservation_params)
      @reservation.change_capacity                           # 予約日に紐づくcapacityから予約人数をマイナスする
      @reservation.full?                                     # 席数が0になった場合にcapacityステータスを満席に変更する。
      ReservationMailer.email(@reservation).deliver_now      # 入力されたメールアドレスに確認メールを送信
      view_context.reservation_to_slack                      # 予約の登録をSlackへ通知
    end
    redirect_to root_path, success: 'ご予約が完了しました。'
  rescue StandardError
    redirect_to reservations_path, danger: 'ご予約ができませんでした。店舗までご連絡下さい。'
    view_context.reservation_error_to_slack
  end

  private

  def reservation_params
    params.require(:reservation).permit(:name, :email, :phonenumber, :number_of_people, :visiting_time, :reservation_status, :user_id, :capacity_id)
  end
end

app/views/admin/reservations/_editform.html.erb
<%= form_with model: @reservation, url: admin_reservation_path(@reservation), local: true do |f| %>
  <%= render '/admin/shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name %> *必須
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :email %> *必須
    <%= f.email_field :email, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :phonenumber %> *必須
    <%= f.telephone_field :phonenumber, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :start_time %> *必須
    <%= f.date_field :capacity_id, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :visiting_time %> *必須
    <%= f.select :visiting_time, Reservation.visiting_times_i18n.invert, {}, {class: "form-control", required: true} %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_people %> *必須
    <%= f.select :number_of_people,[["1名", 1],["2名", 2],["3名", 3],["4名", 4],["5名", 5],["6名", 6],["7名", 7],["8名", 8],["9名", 9],["10名", 10]], {}, {class: "form-control", required: true} %>
  </div>
  <div class="form-group">
    <%= f.label :reservation_status %>
    <%= f.select :reservation_status, Reservation.reservation_statuses_i18n.invert, {}, {class: "form-control", required: true} %>
  </div>
  <div class="form-group">
    <%= f.label :reservation_media %> *必須
    <%= f.select :reservation_media, Reservation.reservation_media_i18n.invert, {}, {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :remarks %>
    <%= f.text_area :remarks, class: "form-control", rows: "3"%>
  </div>
  <%= f.submit "変更", class: "btn btn-primary" %>
<% end %>

app/views/admin/reservations/_form.html.erb
<%= form_with model: @reservation, url: admin_reservations_path, local: true do |f| %>
  <div class="form-group">
    <%= f.label :user_id %> *user登録されてるuserの場合アカウントのIDを入力
    <%= f.text_field :user_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :name %> *必須
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :email %> *必須
    <%= f.email_field :email, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :phonenumber %> *必須
    <%= f.telephone_field :phonenumber, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :start_time %> *必須
    <%= f.date_field :capacity_id, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :visiting_time %> *必須
    <%= f.select :visiting_time, Reservation.visiting_times_i18n.invert, {}, {class: 'form-control', required: true} %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_people %> *必須
    <%= f.select :number_of_people,[["1名", 1],["2名", 2],["3名", 3],["4名", 4],["5名", 5],["6名", 6],["7名", 7],["8名", 8],["9名", 9],["10名", 10]], {}, {class: "form-control", required: true} %>
  </div>
  <div class="form-group">
    <%= f.label :reservation_media %> *必須
    <%= f.select :reservation_media, Reservation.reservation_media_i18n.invert, {}, {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :remarks %>
    <%= f.text_area :remarks, class: "form-control", rows: "3"%>
  </div>
  <%= f.submit "予約", class: "btn btn-primary" %>
<% end %>

app/views/admin/reservations/_reservation.html.erb
<tr>
  <td class="text-nowrap">
    <%= l reservation.capacity.start_time, format: :short %>
  </td>
  <td class="text-nowrap">
    <%= reservation.visiting_time %>
  </td>
  <td class="text-nowrap">
    <%= reservation.name %>
  </td>
  <td class="text-nowrap">
    <%= reservation.number_of_people %>
  </td>
  <td class="text-nowrap">
    <%= reservation.reservation_status_i18n %>
  </td>
  <td class="text-nowrap">
    <%= link_to admin_reservation_path(reservation), class: "btn btn-info" do %>
      <i class="fas fa-search-plus"></i>詳細
    <% end%>
    <%= link_to edit_admin_reservation_path(reservation), class: "btn btn-success" do %>
      <i class="far fa-edit"></i>変更
    <% end%>
  </td>
</tr>

app/views/admin/reservations/_status_form.html.erb
<div class="row">
  <div class="col-12 mb-3">
    <%= form_with model:@reservation, url: admin_status_path(@reservation), local: true  do |f| %>
      <div class="row">
        <div class="form-inline align-items-right mx-auto">
          <div class="col-auto">
            <%= f.select :reservation_status, Reservation.reservation_statuses_i18n.invert, {}, {class: "form-control", required: true} %>
          </div>
          <div class="col-auto">
            <%= f.submit "更新",  class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/reservations/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <div class="my-3">
        <h2>予約変更</h2>
      </div>
      <%= render "editform" %>
      <div class="text-center mb-3">
        <%= link_to '一覧へ', admin_reservations_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reservations/index.html.erb
<div class="container p-3 p-md-4 p-lg-5">
  <div class="my-3">
    <h2>予約</h2>
  </div>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= search_form_for @q, url: admin_reservations_path  do |f| %>
        <div class="row">
          <div class="form-inline align-items-center mx-auto">
            <div class="col-auto">
              <%= f.search_field :name_cont, class: "form-control", placeholder: "名前" %>
            </div>
            <div class="col-auto">
              <%= f.submit "検索",  class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-center mb-3">
    <%= link_to "新規予約", new_admin_reservation_path, class: "btn btn-primary" %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col" class="text-nowrap">日にち</th>
              <th scope="col" class="text-nowrap">時間</th>
              <th scope="col" class="text-nowrap">名前</th>
              <th scope="col" class="text-nowrap">人数</th>
              <th scope="col" class="text-nowrap">ステータス</th>
              <th scope="col" class="text-nowrap"></th>
            </tr>
          </thead>
          <tbody>
            <%= render @reservations %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= paginate @reservations %>
  </div>
</div>

app/views/admin/reservations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <div class="my-3">
        <h2>新規予約</h2>
      </div>
      <%= render "form" %>
      <div class="text-center mb-3">
        <%= link_to "一覧へ", admin_reservations_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reservations/show.html.erb
<div class="container p-3 p-md-4 p-lg-5">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="my-3">
        <h2>予約詳細</h2>
      </div>
      <%= render "status_form" %>
      <div class="text-right mb-3">
        <%= link_to edit_admin_reservation_path(@reservation), class: "btn btn-success" do %>
          <i class="far fa-edit"></i>予約変更
        <% end %>
        <%= link_to admin_cancel_path(@reservation), method: :patch, data: {confirm: "本当にキャンセルしてもよろしいですか?"}, class: "btn btn-warning" do %>
          <i class="fas fa-ban"></i>キャンセル
        <% end %>
        <%= link_to admin_reservation_path(@reservation), method: :delete, data: { confirm: "２度と戻せません本当に削除してもよろしいですか"}, class: "btn btn-danger" do %>
          <i class="far fa-trash-alt"></i>削除
        <% end %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row" class="text-nowrap">予約番号</th>
          <td><%= @reservation.id %></td>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">日にち</th>
          <td><%= l @reservation.capacity.start_time, format: :long %></td>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">時間</th>
          <td><%= @reservation.visiting_time %></td>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">人数</th>
          <td><%= @reservation.number_of_people %></td>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">名前</th>
          <td><%= @reservation.name %></td>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">メールアドレス</th>
          <td><%= @reservation.email %></td>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">電話番号</th>
          <td><%= @reservation.phonenumber %></td>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">ステータス</th>
          <td><%= @reservation.reservation_status_i18n %></td>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">予約アカウント</th>
          <% if @reservation.user.present? %>
            <td><%= link_to "#{@reservation.user.name}", admin_user_path(@reservation.user) %></td>
          <% else %>
            <td>ゲスト</td>
          <% end %>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">予約方法</th>
          <td><%= @reservation.reservation_media_i18n %></td>
        </tr>
        <tr>
          <th scope="row" class="text-nowrap">備考</th>
          <td><%= simple_format @reservation.remarks %></td>
        </tr>
      </table>
      <div class="text-center mb-3">
        <%= link_to "一覧へ", admin_reservations_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>