config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'shop', to: 'static_pages#shop'

  resources :reservations, only: %i[index create]
  post 'reservations/confirm'
  post 'reservations/back'

  resources :contacts, only: %i[index create]
  post 'contacts/confirm'
  post 'contacts/back'

  resources :users, only: %i[new create]
  get '/mypage', to: 'users#show'
  get '/mypage/edit', to: 'users#edit'
  patch '/mypage/edit', to: 'users#update'
  post 'users/confirm'
  post 'users/back'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: %i[new create edit update]

  resources :news, only: %i[index show]
  resources :menus, only: %i[index]

  namespace :admin do
    root 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    post 'guest_login', to: 'user_sessions#guest_login'
    delete 'logout', to: 'user_sessions#destroy'
    resources :news
    resources :menus
    resources :users, only: %i[index show edit update destroy]
    resources :reservations
    patch '/reservations/cancel/:id', to: 'reservations#cancel', as: :cancel
    patch '/reservations/status/:id', to: 'reservations#status_update', as: :status
    resources :contacts, only: %i[index show update destroy]
    resources :capacities, only: %i[index show edit update]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :reservations

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)\w{8,36}\z/.freeze
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  VALID_PHONE_REGEX = /\A\d{10,11}\z/.freeze

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: { case_sensitive: true }, format: { with: VALID_EMAIL_REGEX, message: 'は正しいメールアドレスを入力してください' }, length: { maximum: 256 }
  validates :phonenumber, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_PHONE_REGEX, message: 'は正しい電話番号を入力してください' }, length: { in: 10..11 }
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は半角英字・数字を混ぜて8文字以上36文字以内にしてください' }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  enum role: { general: 0, admin: 1 }

  # ページネーションのページ数を個別に設定
  PER_PAGE = 5

  # ゲストログイン用アカウント
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'ゲスト'
      user.phonenumber = '00000000000'
      user.password = 'guest0000'
      user.password_confirmation = 'guest0000'
      user.role = 1
    end
  end

  # コントローラーで機能制限のためゲストユーザーを定義
  GUEST_USER = 'guest@example.com'.freeze
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :ensure_normal_user, only: %i[update destroy]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(created_at: :desc).page(params[:page])
  end

  def show
    @reservations = @user.reservations.order(created_at: :desc).page(params[:page]).per(User::PER_PAGE)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), success: 'アカウント情報を編集しました'
    else
      flash.now['danger'] = 'アカウント情報の変更に失敗しました'
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to admin_users_path, success: 'アカウントを削除しました'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_normal_user
    return unless current_user.email == User::GUEST_USER

    redirect_to admin_root_path, danger: 'ゲストユーザーでは編集・削除できません。'
  end

  def user_params
    params.require(:user).permit(:name, :email, :phonenumber, :role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[show edit update]
  before_action :ensure_normal_user, only: %i[update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: '会員登録が完了しました。'
    else
      flash.now[:danger] = '会員登録に失敗しました。'
      render :new
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  def back
    @user = User.new(user_params)
    render :new
  end

  def show; end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to mypage_path, success: '登録情報を更新しました。'
    else
      flash.now[:danger] = '登録情報の更新に失敗しました。'
      render :edit
    end
  end

  private

  def ensure_normal_user
    return unless current_user.email == User::GUEST_USER

    redirect_to mypage_path, danger: 'ゲストユーザーは編集できません。'
  end

  def user_params
    params.require(:user).permit(:name, :email, :phonenumber, :password, :password_confirmation)
  end
end

app/views/users/_back_form.html.erb
<%= form_with model: @user, url: users_back_path, local: true do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :phonenumber %>
  <div class="actions text-center mb-5">
    <%= f.submit "入力画面に戻る", class: "btn btn-secondary w-100" %>
  </div>
<% end %>

app/views/users/_confirm_form.html.erb
<%= form_with model: @user, local: true do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :phonenumber %>
  <%= f.hidden_field :password %>
  <%= f.hidden_field :password_confirmation %>
  <div class="actions text-center my-2">
    <%= f.submit "登録する", class: "btn btn-success w-100" %>
  </div>
<% end %>

app/views/users/_editform.html.erb
<%= form_with model: @user, url: mypage_edit_path, local: true, id: "user_form" do |f| %>
  <table class="table table-bordered bg-white">
    <tr>
      <th scope="row" class="table-active text-center align-middle"><%= f.label :name %></th>
      <td><%= f.text_field :name, class: "form-control", placeholder: "(例)オーシャン太郎", required: true %></td>
    </tr>
    <tr>
      <th scope="row" class="table-active text-center align-middle"><%= f.label :email %></th>
      <td><%= f.email_field :email, class: "form-control", placeholder: "(例)lunchcafe@ocean.com", required: true %></td>
    </tr>
    <tr>
      <th scope="row" class="table-active text-center align-middle"><%= f.label :phonenumber %></th>
      <td><%= f.telephone_field :phonenumber, class: "form-control", placeholder: "(例)09012345678", required: true %></td>
    </tr>
  </table>
  <div class="actions text-center my-4">
    <%= f.submit "更新", class: "btn btn-success w-100" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user, method: :post, url: users_confirm_path, local: true, id: "user_form" do |f| %>
  <div class="form-group">
    <div class="text-left mb-1">
      <%= f.label :name %>
    </div>
    <div class="mb-3">
      <%= f.text_field :name, value: current_user&.name, class: "form-control", placeholder: "(例)オーシャン太郎", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="text-left mb-1">
      <%= f.label :email %>
    </div>
    <div class="mb-3">
      <%= f.email_field :email, value: current_user&.email, class: "form-control", placeholder: "(例)lunchcafe@ocean.com", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="text-left mb-1">
      <%= f.label :phonenumber %>
    </div>
    <div class="mb-3">
      <%= f.telephone_field :phonenumber, value: current_user&.phonenumber, class: "form-control", placeholder: "(例)09012345678", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="text-left mb-1">
      <%= f.label :password %>
    </div>
    <div class="mb-3">
      <%= f.password_field :password, class: "form-control", placeholder: "8文字以上32字以内の半角英数字", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="text-left mb-1">
      <%= f.label :password_confirmation , "パスワード(確認用)"%>
    </div>
    <div class="mb-3">
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "パスワードを再度入力", required: true %>
    </div>
  </div>
  <div class="text-left">
    <small>・会員登録をして頂くと簡単にご予約ができるようになります。</small><br>
    <small>・全ての入力項目が必須となっております。</small><br>
    <small>・電話番号はハイフンを除き市外局番から記入をお願いいたします。</small><br>
    <small>・英数字は半角での記入をお願いいたします。</small><br>
  </div>
  <div class="actions text-center my-2">
    <%= f.submit "規約に同意して次へ", class: "btn btn-success w-100" %>
  </div>
<% end %>

app/views/users/confirm.html.erb
<% content_for(:title, "会員登録内容確認") %>
<div class="container user-margin">
  <h2 class="text-center my-5">会員登録内容確認</h2>
  <div class="row">
    <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row" class="table-active text-center align-middle">お名前</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row" class="table-active text-center align-middle">メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th scope="row" class="table-active text-center align-middle">電話番号</th>
          <td><%= @user.phonenumber %></td>
        </tr>
      </table>
      <%= render "confirm_form" %>
      <%= render "back_form" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for(:title, "会員情報変更") %>
<div class="container">
  <div class="my-4">
    <% breadcrumb :edit_mypage %>
    <%= breadcrumbs edit_mypage: " &rsaquo; " %>
  </div>
  <h2 class="text-center my-5">会員情報変更</h2>
  <div class="row">
    <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <%= render "editform" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:title, "会員登録") %>
<div class="container">
  <div class="my-4">
    <% breadcrumb :user %>
    <%= breadcrumbs user: " &rsaquo; " %>
  </div>
  <h2 class="text-center my-5">会員登録</h2>
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3 border p-3 mb-4">
      <%= render "form" %>
      <div class="text-center my-3">
        <small><%= link_to "利用規約", terms_path %>、<%= link_to "プライバシーポリシー", privacy_path %>をご確認の上、ボタンを押してください。</small>
      </div>
    </div>
    <div class="col-12 text-center mb-5">
      <%= link_to "ログインページへ", login_path %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:title, "マイページ") %>
<div class="container">
  <div class="my-4">
    <% breadcrumb :mypage %>
    <%= breadcrumbs mypage: " &rsaquo; " %>
  </div>
  <h1 class="text-center my-5"><i class="fas fa-user"></i>マイページ</h1>
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h3 class="text-center mb-3">
        登録情報
        <%= link_to  "mypage/edit" do %>
          <i class="fas fa-cog"></i>
        <% end %>
      </h3>
      <div class="table-responsive">
        <table class="table table-bordered bg-white shadow mb-5">
          <tr>
            <th scope="row" class="text-nowrap">お名前</th>
            <td><%= current_user.name%></td>
          </tr>
          <tr>
            <th scope="row" class="text-nowrap">メールアドレス</th>
            <td><%= current_user.email%></td>
          </tr>
          <tr>
            <th scope="row" class="text-nowrap">電話番号</th>
            <td><%= current_user.phonenumber %></td>
          </tr>
        </table>
      </div>
      <div class="text-center mb-4">
        <%= link_to logout_path, class: "btn btn-secondary w-50 text-nowrap", method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>ログアウト
        <% end %>
      </div>
    </div>
  </div>
</div>