config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'shop', to: 'static_pages#shop'

  resources :reservations, only: %i[index create]
  post 'reservations/confirm'
  post 'reservations/back'

  resources :contacts, only: %i[index create]
  post 'contacts/confirm'
  post 'contacts/back'

  resources :users, only: %i[new create]
  get '/mypage', to: 'users#show'
  get '/mypage/edit', to: 'users#edit'
  patch '/mypage/edit', to: 'users#update'
  post 'users/confirm'
  post 'users/back'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: %i[new create edit update]

  resources :news, only: %i[index show]
  resources :menus, only: %i[index]

  namespace :admin do
    root 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    post 'guest_login', to: 'user_sessions#guest_login'
    delete 'logout', to: 'user_sessions#destroy'
    resources :news
    resources :menus
    resources :users, only: %i[index show edit update destroy]
    resources :reservations
    patch '/reservations/cancel/:id', to: 'reservations#cancel', as: :cancel
    patch '/reservations/status/:id', to: 'reservations#status_update', as: :status
    resources :contacts, only: %i[index show update destroy]
    resources :capacities, only: %i[index show edit update]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/shared/_flash_message.html.erb
<% if flash.any? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% key = "success" if key == "success" %>
      <% key = "error" if key == "danger" %>
      toastr['<%= key %>']('<%= value %>');
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<div class='container py-3'>
  <div class='row'>
    <div class='col-12'>
      <div class="text-center my-2">
        <%= link_to "https://www.twitter.com/", target: :_blank, rel: "noopener noreferrer" do %>
          <i class="fab fa-twitter fa-2x mr-1 footer-text"></i>
        <% end %>
        <%= link_to "https://www.instagram.com/", target: :_blank, rel: "noopener noreferrer" do %>
          <i class="fab fa-instagram fa-2x mr-1 footer-text"></i>
        <% end %>
      </div>
      <div class="text-center footer-text">
        <%= link_to "利用規約", terms_path, class:"footer-text" %> / 
        <%= link_to "プライバシーポリシー", privacy_path, class:"footer-text" %>
        <div class='copyright'>
          <p>Copyright © 2022. LunchCafeOcean</p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light fixed-top shadow navbar-expand-lg">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("logo.jpg")%>
  <% end %>
  <div class="navbar-nav ml-auto d-block d-lg-none">
    <%= link_to reservations_path do %>
      <div class="flex-column text-center">
        <i class="fas fa-calendar-check fa-2x"></i>
        <p class="text-nowrap mb-0 small">Web予約</p>
      </div>
    <% end %>
  </div>
  <div class="navbar-nav d-block d-lg-none">
    <% if logged_in? %>
      <%= link_to mypage_path do %>
        <div class="flex-column mx-3 text-center">
          <i class="fas fa-user fa-2x"></i>
          <p class="text-nowrap mb-0 small">マイページ</p>
        </div>
      <% end %>
    <%else%>
      <%= link_to admin_guest_login_path, method: :post do %>
        <div class="flex-column mx-3 text-center">
          <i class="fas fa-sign-in-alt fa-2x"></i>
          <p class="text-nowrap mb-0 small">管理画面へ</p>
        </div>
      <% end %>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav mr-auto ml-3">
      <li class= "nav-item"><%= link_to "Home", root_path, class: "dropdown-item" %></li>
      <li><%= link_to "お知らせ", news_index_path, class: "dropdown-item" %></li>
      <li><%= link_to "メニュー", menus_path, class: "dropdown-item" %></li>
      <li><%= link_to "店舗情報", shop_path, class: "dropdown-item" %></li>
      <li><%= link_to "お問い合わせ", contacts_path, class: "dropdown-item" %></li>
    </ul>
  </div>
  <div class="navbar-nav mr-auto d-none d-lg-block">
    <%= link_to reservations_path do %>
      <div class="flex-column mx-3 text-center">
        <i class="fas fa-calendar-check fa-2x"></i>
        <p class="text-nowrap mb-0">Web予約</p>
      </div>
    <% end %>
  </div>
  <div class="navbar-nav mr-auto d-none d-lg-block">
    <% if logged_in? %>
      <%= link_to mypage_path do %>
        <div class="flex-column mx-3 mb-0 text-center">
          <i class="fas fa-user fa-2x"></i>
          <p class="text-nowrap mb-0">マイページ</p>
        </div>
      <% end %>
    <%else%>
      <%= link_to admin_guest_login_path, method: :post do %>
        <div class="flex-column mx-3 mb-0 text-center">
          <i class="fas fa-sign-in-alt fa-2x"></i>
          <p class="text-nowrap mb-0">ゲストログイン</p>
        </div>
      <% end %>
    <% end %>
  </div>
</nav>