config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'shop', to: 'static_pages#shop'

  resources :reservations, only: %i[index create]
  post 'reservations/confirm'
  post 'reservations/back'

  resources :contacts, only: %i[index create]
  post 'contacts/confirm'
  post 'contacts/back'

  resources :users, only: %i[new create]
  get '/mypage', to: 'users#show'
  get '/mypage/edit', to: 'users#edit'
  patch '/mypage/edit', to: 'users#update'
  post 'users/confirm'
  post 'users/back'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: %i[new create edit update]

  resources :news, only: %i[index show]
  resources :menus, only: %i[index]

  namespace :admin do
    root 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    post 'guest_login', to: 'user_sessions#guest_login'
    delete 'logout', to: 'user_sessions#destroy'
    resources :news
    resources :menus
    resources :users, only: %i[index show edit update destroy]
    resources :reservations
    patch '/reservations/cancel/:id', to: 'reservations#cancel', as: :cancel
    patch '/reservations/status/:id', to: 'reservations#status_update', as: :status
    resources :contacts, only: %i[index show update destroy]
    resources :capacities, only: %i[index show edit update]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :reservations

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)\w{8,36}\z/.freeze
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  VALID_PHONE_REGEX = /\A\d{10,11}\z/.freeze

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: { case_sensitive: true }, format: { with: VALID_EMAIL_REGEX, message: 'は正しいメールアドレスを入力してください' }, length: { maximum: 256 }
  validates :phonenumber, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_PHONE_REGEX, message: 'は正しい電話番号を入力してください' }, length: { in: 10..11 }
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は半角英字・数字を混ぜて8文字以上36文字以内にしてください' }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  enum role: { general: 0, admin: 1 }

  # ページネーションのページ数を個別に設定
  PER_PAGE = 5

  # ゲストログイン用アカウント
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'ゲスト'
      user.phonenumber = '00000000000'
      user.password = 'guest0000'
      user.password_confirmation = 'guest0000'
      user.role = 1
    end
  end

  # コントローラーで機能制限のためゲストユーザーを定義
  GUEST_USER = 'guest@example.com'.freeze
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :ensure_normal_user, only: %i[update destroy]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(created_at: :desc).page(params[:page])
  end

  def show
    @reservations = @user.reservations.order(created_at: :desc).page(params[:page]).per(User::PER_PAGE)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), success: 'アカウント情報を編集しました'
    else
      flash.now['danger'] = 'アカウント情報の変更に失敗しました'
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to admin_users_path, success: 'アカウントを削除しました'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_normal_user
    return unless current_user.email == User::GUEST_USER

    redirect_to admin_root_path, danger: 'ゲストユーザーでは編集・削除できません。'
  end

  def user_params
    params.require(:user).permit(:name, :email, :phonenumber, :role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[show edit update]
  before_action :ensure_normal_user, only: %i[update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: '会員登録が完了しました。'
    else
      flash.now[:danger] = '会員登録に失敗しました。'
      render :new
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  def back
    @user = User.new(user_params)
    render :new
  end

  def show; end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to mypage_path, success: '登録情報を更新しました。'
    else
      flash.now[:danger] = '登録情報の更新に失敗しました。'
      render :edit
    end
  end

  private

  def ensure_normal_user
    return unless current_user.email == User::GUEST_USER

    redirect_to mypage_path, danger: 'ゲストユーザーは編集できません。'
  end

  def user_params
    params.require(:user).permit(:name, :email, :phonenumber, :password, :password_confirmation)
  end
end

app/views/admin/users/_form.html.erb
<%= form_with model: @user, url: admin_user_path(@user), local: true do |f| %>
  <%= render '/admin/shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :phonenumber %>
    <%= f.telephone_field :phonenumber, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :role %>
    <%= f.text_field :role, class: "form-control", required: true %>
  </div>
  <%= f.submit "更新", class: "btn btn-primary" %>
<% end %>

app/views/admin/users/_reservation.html.erb
<tr>
  <td class="text-nowrap">
    <%= l reservation.capacity.start_time, format: :long%>
  </td>
  <td class="text-nowrap">
    <%= reservation.visiting_time %>
  </td>
  <td class="text-nowrap">
    <%= reservation.number_of_people %>名
  </td>
  <td class="text-nowrap">
    <%= reservation.reservation_status_i18n %>
  </td>
  <td class="text-nowrap">
    <%= link_to admin_reservation_path(reservation), class: "btn btn-info" do %>
      <i class="fas fa-search-plus"></i>詳細
    <% end%>
  </td>
</tr>

app/views/admin/users/_user.html.erb
<tr>
  <td class="text-nowrap">
    <%= user.name %>
  </td>
  <td class="text-nowrap text-right mr-1">
    <%= link_to admin_user_path(user), class: "btn btn-info" do %>
      <i class="fas fa-search-plus"></i>詳細
    <% end%>
    <%= link_to edit_admin_user_path(user), class: "btn btn-success" do %>
      <i class="far fa-edit"></i>編集
    <% end%>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <div class="my-3">
        <h2>ユーザー編集</h2>
      </div>
      <%= render "form" %>
      <div class="text-center mb-3">
        <%= link_to "一覧へ", admin_users_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container p-3 p-md-4 p-lg-5">
  <div class="my-3">
    <h2>ユーザー</h2>
  </div>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= search_form_for @q, url: admin_users_path  do |f| %>
        <div class="row">
          <div class="form-inline align-items-center mx-auto">
            <div class="col-auto">
              <%= f.search_field :name_cont, class: "form-control", placeholder: "名前" %>
            </div>
            <div class="col-auto">
              <%= f.submit "検索",  class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col" class="text-nowrap">名前</th>
              <th scope="col" class="text-nowrap"></th>
            </tr>
          </thead>
          <tbody>
            <%= render @users %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= paginate @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container p-3 p-md-4 p-lg-5">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="my-3">
        <h2>ユーザー詳細</h2>
      </div>
      <div class="text-right mb-3">
        <%= link_to edit_admin_user_path(@user), class: "btn btn-success" do %>
          <i class="far fa-edit"></i>編集
        <% end %>
        <%= link_to admin_user_path(@user), method: :delete, data: { confirm: "２度と戻せません本当に削除してもよろしいですか"}, class: "btn btn-danger" do %>
          <i class="far fa-trash-alt"></i>削除
        <% end %>
      </div>
      <table class="table table-bordered bg-white mb-5">
        <tr>
          <th scope="row">ID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th scope="row">名前</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row">ユーザー権限</th>
          <td><%= @user.role %></td>
        </tr>
        <tr>
          <th scope="row">メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th scope="row">電話番号</th>
          <td><%= @user.phonenumber %></td>
        </tr>
        <tr>
          <th scope="row">登録日時</th>
          <td><%= l @user.created_at, format: :short %></td>
        </tr>
      </table>
      <div class="my-3">
        <h2>予約履歴</h2>
      </div>
      <div class="table-responsive">
        <table class="table table-bordered bg-white">
          <thead>
            <tr>
              <th scope="col">来店日</th>
              <th scope="col">時間</th>
              <th scope="col">人数</th>
              <th scope="col">ステータス</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "admin/users/reservation", collection:  @reservations %>
          </tbody>
        </table>
      </div>
      <div class="row justify-content-center">
        <%= paginate @reservations %>
      </div>
      <div class="text-center mb-3">
        <%= link_to "一覧へ", admin_reservations_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>